import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { logAuditAction } from "@/lib/auditLog";

export interface SupportTicket {
  id: string;
  ticket_number: string;
  customer_id?: string | null;
  customer_name: string;
  customer_email: string;
  customer_phone: string | null;
  subject: string;
  description: string | null;
  status: 'open' | 'in_progress' | 'waiting' | 'resolved' | 'closed';
  priority: 'low' | 'medium' | 'high' | 'urgent';
  category: string | null;
  assigned_to: string | null;
  tags?: string[];
  first_response_at?: string | null;
  response_time_seconds?: number | null;
  user_id?: string | null;
  created_at: string;
  updated_at: string;
}

export interface TicketReply {
  id: string;
  ticket_id: string;
  sender_type: string | null;
  sender_id?: string | null;
  user_id?: string | null;
  sender_name: string | null;
  message: string;
  content?: string;
  attachments: any;
  is_internal?: boolean;
  created_at: string;
}

export interface CreateTicketData {
  customer_name: string;
  customer_email: string;
  customer_phone?: string;
  subject: string;
  description?: string;
  priority?: 'low' | 'medium' | 'high' | 'urgent';
  category?: string;
}

export interface CreateReplyData {
  ticket_id: string;
  content: string;
  sender_name?: string;
}

export function useSupportTickets() {
  const queryClient = useQueryClient();

  // Fetch all tickets
  const { data: tickets = [], isLoading, error } = useQuery({
    queryKey: ["support-tickets"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("support_tickets")
        .select("*")
        .is("deleted_at", null)
        .order("created_at", { ascending: false });

      if (error) throw error;
      return (data || []).map((item): SupportTicket => ({
        id: item.id,
        ticket_number: item.ticket_number,
        customer_id: (item as any).customer_id ?? null,
        customer_name: item.customer_name,
        customer_email: item.customer_email,
        customer_phone: item.customer_phone,
        subject: item.subject,
        description: item.description,
        status: item.status as SupportTicket['status'],
        priority: item.priority as SupportTicket['priority'],
        category: item.category,
        assigned_to: item.assigned_to,
        tags: (item as any).tags ?? [],
        first_response_at: item.first_response_at,
        response_time_seconds: item.response_time_seconds,
        user_id: item.user_id,
        created_at: item.created_at,
        updated_at: item.updated_at,
      }));
    },
  });

  // Create ticket
  const createTicket = useMutation({
    mutationFn: async (ticketData: CreateTicketData) => {
      const { data, error } = await supabase
        .from("support_tickets")
        .insert({
          customer_name: ticketData.customer_name,
          customer_email: ticketData.customer_email,
          customer_phone: ticketData.customer_phone || null,
          subject: ticketData.subject,
          description: ticketData.description || '',
          priority: ticketData.priority || 'medium',
          category: ticketData.category || null,
          ticket_number: '', // Will be auto-generated by trigger
        })
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["support-tickets"] });
      logAuditAction({ action: "create", resource_type: "support_ticket", resource_id: data.id, description: `Support ticket created: ${data.subject}` });
      toast.success("Ticket created successfully");
    },
    onError: (error) => {
      console.error("Error creating ticket:", error);
      toast.error("Failed to create ticket");
    },
  });

  // Update ticket status
  const updateTicketStatus = useMutation({
    mutationFn: async ({ id, status }: { id: string; status: SupportTicket['status'] }) => {
      const { error } = await supabase
        .from("support_tickets")
        .update({ status })
        .eq("id", id);

      if (error) throw error;
    },
    onSuccess: (_d, vars) => {
      queryClient.invalidateQueries({ queryKey: ["support-tickets"] });
      logAuditAction({ action: "status_change", resource_type: "support_ticket", resource_id: vars.id, description: `Ticket status → ${vars.status}`, new_value: { status: vars.status } });
      toast.success("Ticket status updated");
    },
    onError: (error) => {
      console.error("Error updating ticket status:", error);
      toast.error("Failed to update status");
    },
  });

  // Update ticket priority
  const updateTicketPriority = useMutation({
    mutationFn: async ({ id, priority }: { id: string; priority: SupportTicket['priority'] }) => {
      const { error } = await supabase
        .from("support_tickets")
        .update({ priority })
        .eq("id", id);

      if (error) throw error;
    },
    onSuccess: (_d, vars) => {
      queryClient.invalidateQueries({ queryKey: ["support-tickets"] });
      logAuditAction({ action: "update", resource_type: "support_ticket", resource_id: vars.id, description: `Ticket priority → ${vars.priority}`, new_value: { priority: vars.priority } });
      toast.success("Priority updated");
    },
    onError: (error) => {
      console.error("Error updating priority:", error);
      toast.error("Failed to update priority");
    },
  });

  // Assign ticket
  const assignTicket = useMutation({
    mutationFn: async ({ id, assigned_to }: { id: string; assigned_to: string | null }) => {
      const { error } = await supabase
        .from("support_tickets")
        .update({ assigned_to })
        .eq("id", id);

      if (error) throw error;
    },
    onSuccess: (_d, vars) => {
      queryClient.invalidateQueries({ queryKey: ["support-tickets"] });
      logAuditAction({ action: "update", resource_type: "support_ticket", resource_id: vars.id, description: `Ticket assigned to ${vars.assigned_to || "unassigned"}`, new_value: { assigned_to: vars.assigned_to } });
      toast.success("Ticket assigned");
    },
    onError: (error) => {
      console.error("Error assigning ticket:", error);
      toast.error("Failed to assign ticket");
    },
  });

  // Soft delete ticket (move to trash)
  const deleteTicket = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from("support_tickets")
        .update({ deleted_at: new Date().toISOString() } as any)
        .eq("id", id);

      if (error) throw error;
      return id;
    },
    onSuccess: (_data, id) => {
      queryClient.invalidateQueries({ queryKey: ["support-tickets"] });
      toast.success("Ticket moved to trash", {
        action: {
          label: "Undo",
          onClick: async () => {
            await supabase.from("support_tickets").update({ deleted_at: null } as any).eq("id", id);
            queryClient.invalidateQueries({ queryKey: ["support-tickets"] });
          },
        },
        duration: 5000,
      });
    },
    onError: (error) => {
      console.error("Error trashing ticket:", error);
      toast.error("Failed to move to trash");
    },
  });

  // Bulk soft delete tickets
  const bulkDeleteTickets = useMutation({
    mutationFn: async (ids: string[]) => {
      const { error } = await supabase
        .from("support_tickets")
        .update({ deleted_at: new Date().toISOString() } as any)
        .in("id", ids);

      if (error) throw error;
      return ids;
    },
    onSuccess: (_data, ids) => {
      queryClient.invalidateQueries({ queryKey: ["support-tickets"] });
      toast.success(`${ids.length} ticket(s) moved to trash`, {
        action: {
          label: "Undo",
          onClick: async () => {
            await supabase.from("support_tickets").update({ deleted_at: null } as any).in("id", ids);
            queryClient.invalidateQueries({ queryKey: ["support-tickets"] });
          },
        },
        duration: 5000,
      });
    },
    onError: (error) => {
      console.error("Error bulk trashing tickets:", error);
      toast.error("Failed to move to trash");
    },
  });

  // Bulk update ticket status
  const bulkUpdateStatus = useMutation({
    mutationFn: async ({ ids, status }: { ids: string[]; status: SupportTicket['status'] }) => {
      const { error } = await supabase
        .from("support_tickets")
        .update({ status })
        .in("id", ids);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["support-tickets"] });
      toast.success("Status updated");
    },
    onError: (error) => {
      console.error("Error bulk updating status:", error);
      toast.error("Failed to update");
    },
  });

  // Bulk assign tickets
  const bulkAssignTickets = useMutation({
    mutationFn: async ({ ids, assigned_to }: { ids: string[]; assigned_to: string | null }) => {
      const { error } = await supabase
        .from("support_tickets")
        .update({ assigned_to })
        .in("id", ids);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["support-tickets"] });
      toast.success("Tickets assigned");
    },
    onError: (error) => {
      console.error("Error bulk assigning tickets:", error);
      toast.error("Failed to assign");
    },
  });

  // Update ticket tags
  const updateTicketTags = useMutation({
    mutationFn: async ({ id, tags }: { id: string; tags: string[] }) => {
      const { error } = await supabase
        .from("support_tickets")
        .update({ tags } as any)
        .eq("id", id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["support-tickets"] });
      toast.success("Tags updated");
    },
    onError: (error) => {
      console.error("Error updating tags:", error);
      toast.error("Failed to update tags");
    },
  });

  // Stats
  const stats = {
    total: tickets.length,
    open: tickets.filter(t => t.status === 'open').length,
    inProgress: tickets.filter(t => t.status === 'in_progress').length,
    waiting: tickets.filter(t => t.status === 'waiting').length,
    resolved: tickets.filter(t => t.status === 'resolved').length,
    closed: tickets.filter(t => t.status === 'closed').length,
    pending: tickets.filter(t => t.status !== 'resolved' && t.status !== 'closed').length,
  };

  return {
    tickets,
    isLoading,
    error,
    stats,
    createTicket: createTicket.mutate,
    updateTicketStatus: updateTicketStatus.mutate,
    updateTicketPriority: updateTicketPriority.mutate,
    assignTicket: assignTicket.mutate,
    deleteTicket: deleteTicket.mutate,
    bulkDeleteTickets: bulkDeleteTickets.mutate,
    bulkUpdateStatus: bulkUpdateStatus.mutate,
    bulkAssignTickets: bulkAssignTickets.mutate,
    updateTicketTags: updateTicketTags.mutate,
    isCreating: createTicket.isPending,
    isBulkDeleting: bulkDeleteTickets.isPending,
    isBulkUpdating: bulkUpdateStatus.isPending || bulkAssignTickets.isPending,
  };
}

// Hook for ticket replies
export function useTicketReplies(ticketId: string | null) {
  const queryClient = useQueryClient();

  const { data: replies = [], isLoading } = useQuery({
    queryKey: ["ticket-replies", ticketId],
    queryFn: async () => {
      if (!ticketId) return [];
      
      const { data, error } = await supabase
        .from("ticket_replies")
        .select("*")
        .eq("ticket_id", ticketId)
        .order("created_at", { ascending: true });

      if (error) throw error;
      return (data || []).map((item): TicketReply => ({
        id: item.id,
        ticket_id: item.ticket_id,
        sender_type: item.sender_type,
        sender_id: (item as any).sender_id ?? null,
        user_id: item.user_id,
        sender_name: item.sender_name,
        message: item.message,
        content: item.message,
        attachments: item.attachments,
        is_internal: item.is_internal,
        created_at: item.created_at,
      }));
    },
    enabled: !!ticketId,
  });

  const createReply = useMutation({
    mutationFn: async (replyData: CreateReplyData) => {
      const { data: userData } = await supabase.auth.getUser();
      
      const { data, error } = await supabase
        .from("ticket_replies")
        .insert({
          ticket_id: replyData.ticket_id,
          message: replyData.content,
          sender_type: 'admin',
          user_id: userData.user?.id || null,
          sender_name: replyData.sender_name || 'Admin',
        })
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["ticket-replies", ticketId] });
      toast.success("Reply sent successfully");
    },
    onError: (error) => {
      console.error("Error creating reply:", error);
      toast.error("Failed to send reply");
    },
  });

  return {
    replies,
    isLoading,
    createReply: createReply.mutate,
    isCreatingReply: createReply.isPending,
  };
}
